version: '2'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: db
    volumes:
      - ./data-docker:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=userservice
